# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
# title: TIM VO
# description: Jekyll microtheme that looks like JSON
# baseurl: ""
# url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: "tim vo <img src='assets/images/vn-flag.png' alt='VN' style='height: 1.5em;position: relative; top: 5px;'><img src='assets/images/au-flag.png' alt='AU' style='height: 1.5em;position: relative; top: 5px;'>"
  description:
    - hi there!ğŸ‘‹
    - I am a newbie in a BIM-based world - a pretty old guy in 2D world
    - I am into walking, breathing, photographing and sometime &lt;coding&gt; ğŸ‘¨â€ğŸ’»
    - here, is another side of me - a geek with IT stuff
  resume: assets/checkout
  address:
    - sgn, vi
    - syd, nsw, au
  contact:
    # telegram: timvoau
    email: email@timvo.au
  # demo: https://hacked-jekyll.netlify.app
  # source: https://github.com/piazzai/hacked-jekyll
  profiles:
    instagram: https://www.instagram.com/tim.nhut.vo/
    linkedin: https://www.linkedin.com/in/timnhutvo/
  quote:
    - cá»© Ä‘i rá»“i sáº½ Ä‘áº¿n, cá»© gÃµ rá»“i cá»­a sáº½ má»Ÿ 
    - be grateful for present
    - the brighter you shine, the more shadows you cast

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
