# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
# title: TIM VO
# description: Jekyll microtheme that looks like JSON
# baseurl: ""
# url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: TIM VO
  description:
    - Hi there!ðŸ‘‹
    - I am a structural technician, a newbie in a BIM-based world.
    - I love walking, breathing, photographing and sometime \<coding\>.
    - Here, is another side of me - a geek with IT stuff (^-^)
  resume: assets/toBeUpdate
  address:
    - Strathfield South
    - Sydney, NSW 
    - Australia
  contact:
    # office: Foobar Hall 1.23
    phone: +61 466 508 568
    email: timvo.aus@gmail.com
  # demo: https://hacked-jekyll.netlify.app
  # source: https://github.com/piazzai/hacked-jekyll
  profiles:
    facebook: https://www.facebook.com/tim.nhut.vo/
    # twitter: https://twitter.com
    instagram: https://www.instagram.com/tim.nhut.vo/
    linkedin: https://www.linkedin.com/in/nhutvtm/
    # stackoverflow: https://stackoverflow.com
    github: https://github.com/timmyvo/
  quote:
    - Be grateful for present
    - When the going gets tough, the tough get going

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
